name: starter_project
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.2.0
  meta: ^1.9.1
  retrofit: ^4.0.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
